import "server-only";
import { createAdminSupabaseClient } from "@/lib/supabase/admin";
import { updateProject, updateProjectItem } from "@/backend/repositories";
import { createInvoiceFromProject } from "@/backend/services/finance/invoice-operations";
import { logAuditEvent } from "@/backend/observability/audit";
import type { Json } from "@/types/database";

async function load(projectId:string){const s=createAdminSupabaseClient();const{data,error}=await s.from("projects").select("*, project_items(*, media_assets(evidence_type)), invoices(id,status_code,balance_due_amount)").eq("id",projectId).maybeSingle();if(error)throw error;if(!data)throw new Error("Project not found.");return data;}
export async function updateCloseout(input:{projectId:string;profileId:string;action:string;notes?:string|null;itemIds?:string[];customerName?:string|null;warrantyDays?:number;completionSummary?:string|null}){
 const project=await load(input.projectId);const now=new Date();const s=createAdminSupabaseClient();
 if(input.action==="signoff"){if(!input.customerName?.trim())throw new Error("Customer sign-off name is required.");await updateProject(project.id,{customer_signoff_status:"approved",customer_signed_at:now.toISOString(),customer_signed_by_name:input.customerName.trim()});}
 else if(input.action==="rework"){const ids=input.itemIds??[];if(!ids.length)throw new Error("Select at least one item for rework.");if(!input.notes?.trim())throw new Error("A rework reason is required.");for(const item of project.project_items.filter((i)=>ids.includes(i.id))){await updateProjectItem(item.id,{status_code:"in_progress",completed_at:null,internal_note:input.notes});await s.from("project_item_events").insert({project_id:project.id,project_item_id:item.id,event_type:"qa_rework",reason:input.notes,old_value:{status_code:item.status_code},new_value:{status_code:"in_progress"},created_by_profile_id:input.profileId});await s.from("project_scope_changes").insert({project_id:project.id,project_item_id:item.id,change_type:"rework",status:"approved",description:input.notes,requested_by:"QA review",decided_at:now.toISOString(),decided_by_profile_id:input.profileId,created_by_profile_id:input.profileId});}await updateProject(project.id,{status_code:"in_progress",qa_status:"rework_required",qa_notes:input.notes});}
 else if(input.action==="approve_qa"){if(project.status_code!=="qa_review")throw new Error("Project must be in QA / Review.");const unfinished=project.project_items.filter((i)=>!["completed","deferred"].includes(i.status_code));if(unfinished.length)throw new Error("All work items must be completed or deferred.");for(const item of project.project_items){if(!item.before_after_required)continue;const types=new Set((item.media_assets??[]).map((a)=>a.evidence_type));if(!types.has("before")||!types.has("after"))throw new Error(`Missing required before/after evidence for ${item.title}.`);}if(project.customer_signoff_status!=="approved")throw new Error("Record customer sign-off before approving closeout.");const warrantyDays=Math.max(Number(input.warrantyDays??30),0);const expires=new Date(now.getTime()+warrantyDays*86400000);await updateProject(project.id,{qa_status:"approved",qa_reviewed_at:now.toISOString(),qa_reviewed_by_profile_id:input.profileId,qa_notes:input.notes??null,warranty_starts_at:now.toISOString(),warranty_expires_at:expires.toISOString(),completion_summary:input.completionSummary?.trim()||"All approved work completed, evidence reviewed, and customer sign-off recorded."});await createInvoiceFromProject({projectId:project.id,profileId:input.profileId});}
 else if(input.action==="generate_review_request"){await updateProject(project.id,{review_request_generated_at:now.toISOString()});}
 else if(input.action==="complete"){const invoice=(project.invoices??[]).find((i)=>i.status_code==="paid"&&Number(i.balance_due_amount)===0);if(project.qa_status!=="approved"||project.customer_signoff_status!=="approved"||!invoice)throw new Error("QA approval, customer sign-off, and full payment are required before completion.");await updateProject(project.id,{status_code:"completed",completed_at:now.toISOString()});}
 else throw new Error("Unsupported closeout action.");
 const after=await load(project.id);await logAuditEvent({action:`projects.closeout.${input.action}`,entityType:"project",entityId:project.id,performedByProfileId:input.profileId,oldValue:project as unknown as Json,newValue:after as unknown as Json,metadata:{item_ids:input.itemIds??[],reason:input.notes??null}});return after;
}
