"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
export function PaymentActions({ invoiceId, balance, payments }: { invoiceId:string; balance:number; payments:Array<{id:string;amount:number;status_code:string}> }) {
  const router=useRouter(); const[amount,setAmount]=useState(balance); const[method,setMethod]=useState("bank_transfer"); const[reference,setReference]=useState(""); const[message,setMessage]=useState<string|null>(null); const[proof,setProof]=useState<File|null>(null);
  async function record(){const response=await fetch(`/api/invoices/${invoiceId}/payments`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({amount,method,reference})});const payload=await response.json();if(!response.ok||!payload.success){setMessage(payload.error??"Payment failed.");return}router.refresh();}
  async function verify(id:string){if(proof){const form=new FormData();form.set("file",proof);const upload=await fetch(`/api/payments/${id}/proof`,{method:"POST",body:form});if(!upload.ok){setMessage("Proof upload failed.");return}}const response=await fetch(`/api/payments/${id}/verify`,{method:"POST"});const payload=await response.json();if(!response.ok||!payload.success){setMessage(payload.error??"Verification failed.");return}router.refresh();}
  return <section className="panel page-stack"><div className="panel-header"><div><p className="eyebrow">Payments</p><h2>Payment Reconciliation</h2></div></div>{balance>0?<div className="inline-actions"><input className="input" type="number" value={amount} onChange={e=>setAmount(Number(e.target.value))}/><select className="input input-select" value={method} onChange={e=>setMethod(e.target.value)}><option value="bank_transfer">Bank transfer</option><option value="paynow">PayNow</option><option value="cash">Cash</option><option value="card">Card</option></select><input className="input" value={reference} onChange={e=>setReference(e.target.value)} placeholder="Reference"/><button className="button button-primary" onClick={record}>Record payment</button></div>:null}{payments.map(payment=><div className="review-draft-row" key={payment.id}><span>SGD {Number(payment.amount).toFixed(2)}</span><span>{payment.status_code}</span>{payment.status_code==="processing"?<><input className="input" type="file" accept="image/*" onChange={e=>setProof(e.target.files?.[0]??null)}/><button className="button button-primary" onClick={()=>verify(payment.id)}>Verify</button></>:<a className="button button-secondary" href={`/api/payments/${payment.id}/receipt`}>Receipt PDF</a>}</div>)}{message?<p className="helper-text">{message}</p>:null}</section>;
}
