import Link from "next/link";
import { getOperationsOverview } from "@/backend/services/reports/get-operations-overview";
import { requireAppSession } from "@/lib/auth/session";
import { formatMoney } from "@/frontend/lib/format";
const percent=(value:number)=>`${(value*100).toFixed(1)}%`;const hours=(value:number|null)=>value===null?"—":`${value.toFixed(1)} hr`;
function Metric({label,value,hint}:{label:string;value:string;hint:string}){return <article className="panel report-metric"><p className="report-metric-label">{label}</p><p className="report-metric-value">{value}</p><p className="report-metric-hint">{hint}</p></article>}
export default async function ReportsPage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){await requireAppSession(["owner"]);const p=await searchParams;const one=(key:string)=>typeof p[key]==="string"?p[key] as string:"";const filters={from:one("from"),to:one("to"),workerId:one("workerId"),service:one("service"),source:one("source")};const report=await getOperationsOverview(filters);const query=new URLSearchParams(Object.entries(filters).filter(([,v])=>v));return <div className="page-stack report-page"><section className="page-header"><div><h1>Reports &amp; Performance</h1><p className="helper-text">Operational and financial metrics use the selected date range and dimensions.</p></div><Link className="button button-secondary" href={`/api/reports/export?${query}`}>Export CSV</Link></section>
 <section className="panel"><form className="form-grid" method="get"><label className="field-block"><span className="field-label">From</span><input className="input" type="date" name="from" defaultValue={filters.from}/></label><label className="field-block"><span className="field-label">To</span><input className="input" type="date" name="to" defaultValue={filters.to}/></label><label className="field-block"><span className="field-label">Worker</span><select className="input input-select" name="workerId" defaultValue={filters.workerId}><option value="">All workers</option>{report.filterOptions.workers.map(o=><option value={o.id} key={o.id}>{o.label}</option>)}</select></label><label className="field-block"><span className="field-label">Service</span><select className="input input-select" name="service" defaultValue={filters.service}><option value="">All services</option>{report.filterOptions.services.map(o=><option key={o}>{o}</option>)}</select></label><label className="field-block"><span className="field-label">Lead source</span><select className="input input-select" name="source" defaultValue={filters.source}><option value="">All sources</option>{report.filterOptions.sources.map(o=><option value={o.id} key={o.id}>{o.label}</option>)}</select></label><button className="button button-primary">Apply</button></form></section>
 <section className="stats-grid report-kpi-grid"><Metric label="Lead → Quote" value={percent(report.conversion.leadToQuoteRate)} hint={`${report.conversion.leadsWithQuote} of ${report.conversion.totalLeads} distinct leads`}/><Metric label="Quote → Job" value={percent(report.conversion.quoteToJobRate)} hint={`${report.conversion.quotesWithJob} of ${report.conversion.totalQuotes} quotes`}/><Metric label="Revenue received" value={formatMoney(report.finance.revenue)} hint="Verified payments"/><Metric label="Outstanding" value={formatMoney(report.finance.outstanding)} hint="Open invoice balances"/><Metric label="Tracked cost" value={formatMoney(report.finance.totalCost)} hint="Work-item and purchase costs"/><Metric label="Margin" value={formatMoney(report.finance.margin)} hint={percent(report.finance.marginRate)}/><Metric label="Avg completion" value={hours(report.completion.averageHours)} hint={`${report.completion.completedJobs} completed jobs`}/><Metric label="Complaint rate" value={percent(report.complaints.rate)} hint={`${report.complaints.count} complaint signals`}/></section>
 <section className="report-two-column"><article className="panel"><div className="panel-header"><h2>Lead Sources</h2></div>{report.leadSourceBreakdown.map(row=><div className="review-draft-row report-breakdown-row report-breakdown-row-3" key={row.code}><strong>{row.label}</strong><span>{row.count} leads</span><span>{percent(row.share)}</span></div>)}{!report.leadSourceBreakdown.length?<p className="helper-text">No leads in this selection.</p>:null}</article><article className="panel"><div className="panel-header"><h2>Payment Ageing</h2></div>{report.paymentAgeing.map(row=><div className="review-draft-row report-breakdown-row report-breakdown-row-3" key={row.label}><strong>{row.label}</strong><span>{row.count} invoices</span><span>{formatMoney(row.balance)}</span></div>)}</article></section>
 <section className="report-two-column"><article className="panel"><div className="panel-header"><h2>Worker Utilisation</h2></div>{report.workerUtilisation.map(row=><div className="review-draft-row report-breakdown-row report-breakdown-row-4" key={row.profileId}><strong>{row.displayName}</strong><span>{row.completed}/{row.assigned} completed</span><span>{percent(row.utilisationRate)}</span><span>{row.open} open</span></div>)}</article><article className="panel"><div className="panel-header"><h2>Rework Causes</h2><span>{percent(report.rework.rate)} rate</span></div>{report.rework.causes.map(row=><div className="review-draft-row report-breakdown-row report-breakdown-row-2" key={row.label}><strong>{row.label}</strong><span>{row.count}</span></div>)}{!report.rework.causes.length?<p className="helper-text">No rework recorded.</p>:null}</article></section>
 <section className="panel table-panel"><div className="panel-header"><h2>Service-category Performance</h2></div><div className="table-scroll"><table className="data-table"><thead><tr><th>Service</th><th>Jobs</th><th>Items completed</th><th>Revenue</th><th>Cost</th><th>Margin</th><th>Rework</th></tr></thead><tbody>{report.servicePerformance.map(row=><tr key={row.service}><td>{row.service}</td><td>{row.jobs}</td><td>{row.completed}/{row.items}</td><td>{formatMoney(row.revenue)}</td><td>{formatMoney(row.cost)}</td><td>{formatMoney(row.margin)}</td><td>{row.rework}</td></tr>)}</tbody></table></div></section>
 </div>}
