"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";

type Option = { id: string; label: string };
type Item = {
  id: string; title: string; description: string | null; area_name: string | null; action_summary: string | null;
  customer_note: string | null; internal_note: string | null; quoted_amount: number; actual_cost: number;
  labour_cost: number; material_cost: number; priority_code: string; item_group: string | null; item_type: string | null;
  is_add_on: boolean; add_on_status: string; is_pi: boolean; is_checklist_item: boolean;
  checklist_requirements: string | null; before_after_required: boolean; is_deferred: boolean; deferred_reason: string | null;
  status_code: string; project_item_events?: Array<{ id: string; event_type: string; reason: string | null; created_at: string }>;
};
type Change = { id: string; project_item_id: string | null; change_type: string; status: string; description: string; amount_delta: number; requested_by: string | null; created_at: string };
type TeamMember = { profile_id: string; team_role: string; is_lead: boolean; profile: { display_name: string } | Array<{ display_name: string }> | null };

async function request(url: string, method: string, body?: unknown) {
  const response = await fetch(url, { method, headers: { "Content-Type": "application/json" }, body: body === undefined ? undefined : JSON.stringify(body) });
  const payload = await response.json() as { success?: boolean; error?: string };
  if (!response.ok || !payload.success) throw new Error(payload.error ?? "The action failed.");
}

function Message({ value }: { value: string | null }) { return value ? <p className="helper-text">{value}</p> : null; }

export function ProjectDetailsEditor({ project, contacts, properties, staff }: { project: Record<string, unknown>; contacts: Option[]; properties: Option[]; staff: Option[] }) {
  const router = useRouter(); const [saving, setSaving] = useState(false); const [message, setMessage] = useState<string | null>(null);
  const value = (input: unknown) => typeof input === "string" ? input : "";
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setMessage(null); const form = new FormData(event.currentTarget); try { await request(`/api/projects/${value(project.id)}/management`, "PATCH", Object.fromEntries(form)); setMessage("Project details saved."); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Save failed."); } finally { setSaving(false); } }
  const datetime = (input: unknown) => value(input).slice(0, 16);
  return <form className="stack-form" onSubmit={submit}>
    <div className="form-grid">
      <label className="field-block"><span className="field-label">Project title</span><input className="input" name="title" required defaultValue={value(project.title)}/></label>
      <label className="field-block"><span className="field-label">Coordinator</span><select className="input input-select" name="coordinatorProfileId" defaultValue={value(project.coordinator_profile_id)}><option value="">Unassigned</option>{staff.map(o=><option key={o.id} value={o.id}>{o.label}</option>)}</select></label>
      <label className="field-block"><span className="field-label">Primary customer</span><select className="input input-select" name="primaryContactId" defaultValue={value(project.primary_contact_id)}><option value="">None</option>{contacts.map(o=><option key={o.id} value={o.id}>{o.label}</option>)}</select></label>
      <label className="field-block"><span className="field-label">Primary property</span><select className="input input-select" name="primaryPropertyId" defaultValue={value(project.primary_property_id)}><option value="">None</option>{properties.map(o=><option key={o.id} value={o.id}>{o.label}</option>)}</select></label>
      <label className="field-block"><span className="field-label">Scheduled start</span><input className="input" type="datetime-local" name="scheduledStartAt" defaultValue={datetime(project.scheduled_start_at)}/></label>
      <label className="field-block"><span className="field-label">Scheduled end</span><input className="input" type="datetime-local" name="scheduledEndAt" defaultValue={datetime(project.scheduled_end_at)}/></label>
      <label className="field-block"><span className="field-label">Handover</span><input className="input" type="datetime-local" name="handoverAt" defaultValue={datetime(project.handover_at)}/></label>
      <label className="field-block"><span className="field-label">Payment due</span><input className="input" type="datetime-local" name="paymentDueAt" defaultValue={datetime(project.payment_due_at)}/></label>
      <label className="field-block"><span className="field-label">Payment follow-up</span><input className="input" type="datetime-local" name="paymentFollowUpAt" defaultValue={datetime(project.payment_follow_up_at)}/></label>
      <label className="field-block"><span className="field-label">Warranty starts</span><input className="input" type="datetime-local" name="warrantyStartsAt" defaultValue={datetime(project.warranty_starts_at)}/></label>
      <label className="field-block"><span className="field-label">Warranty expires</span><input className="input" type="datetime-local" name="warrantyExpiresAt" defaultValue={datetime(project.warranty_expires_at)}/></label>
    </div>
    <label className="field-block"><span className="field-label">Scope summary</span><textarea className="input textarea" name="scopeSummary" defaultValue={value(project.scope_summary)}/></label>
    <label className="field-block"><span className="field-label">Internal project remarks</span><textarea className="input textarea" name="remarks" defaultValue={value(project.remarks)}/></label>
    <div className="action-row"><button className="button button-primary" disabled={saving}>{saving?"Saving…":"Save project"}</button><Message value={message}/></div>
  </form>;
}

function WorkItemForm({ projectId, item, onClose }: { projectId: string; item?: Item; onClose?: () => void }) {
  const router = useRouter(); const [saving,setSaving]=useState(false); const [message,setMessage]=useState<string|null>(null); const [isAddOn,setIsAddOn]=useState(item?.is_add_on??false);
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setSaving(true);setMessage(null);const form=new FormData(event.currentTarget);const body={...Object.fromEntries(form),isAddOn:form.has("isAddOn"),isPi:form.has("isPi"),isChecklistItem:form.has("isChecklistItem"),beforeAfterRequired:form.has("beforeAfterRequired")};try{await request(item?`/api/project-items/${item.id}/manage`:`/api/projects/${projectId}/items`,item?"PATCH":"POST",body);setMessage(item?"Work item saved.":"Work item added.");router.refresh();if(!item)(event.currentTarget as HTMLFormElement).reset();onClose?.();}catch(error){setMessage(error instanceof Error?error.message:"Save failed.");}finally{setSaving(false)}}
  return <form className="stack-form work-item-edit-form" onSubmit={submit}><div className="form-grid">
    <label className="field-block"><span className="field-label">Title</span><input className="input" name="title" required defaultValue={item?.title??""}/></label>
    <label className="field-block"><span className="field-label">Area</span><input className="input" name="areaName" defaultValue={item?.area_name??""}/></label>
    <label className="field-block"><span className="field-label">Group</span><input className="input" name="itemGroup" defaultValue={item?.item_group??""}/></label>
    <label className="field-block"><span className="field-label">Type</span><input className="input" name="itemType" defaultValue={item?.item_type??""}/></label>
    <label className="field-block"><span className="field-label">Priority</span><select className="input input-select" name="priorityCode" defaultValue={item?.priority_code??"normal"}><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option></select></label>
    <label className="field-block"><span className="field-label">Quoted amount</span><input className="input" name="quotedAmount" type="number" min="0" step="0.01" defaultValue={item?.quoted_amount??0}/></label>
    <label className="field-block"><span className="field-label">Labour cost</span><input className="input" name="labourCost" type="number" min="0" step="0.01" defaultValue={item?.labour_cost??0}/></label>
    <label className="field-block"><span className="field-label">Material cost</span><input className="input" name="materialCost" type="number" min="0" step="0.01" defaultValue={item?.material_cost??0}/></label>
    <label className="field-block"><span className="field-label">Other actual cost</span><input className="input" name="actualCost" type="number" min="0" step="0.01" defaultValue={item?.actual_cost??0}/></label>
    <label className="toggle-row"><input type="checkbox" name="isAddOn" checked={isAddOn} onChange={e=>setIsAddOn(e.target.checked)}/><span>Add-on</span></label>
    {isAddOn?<label className="field-block"><span className="field-label">Add-on decision</span><select className="input input-select" name="addOnStatus" defaultValue={item?.add_on_status??"proposed"}><option value="proposed">Proposed</option><option value="approved">Approved</option><option value="rejected">Rejected</option></select></label>:null}
    <label className="toggle-row"><input type="checkbox" name="isPi" defaultChecked={item?.is_pi}/><span>Provisional item</span></label><label className="toggle-row"><input type="checkbox" name="isChecklistItem" defaultChecked={item?.is_checklist_item}/><span>Checklist item</span></label><label className="toggle-row"><input type="checkbox" name="beforeAfterRequired" defaultChecked={item?.before_after_required}/><span>Require before/after evidence</span></label>
  </div>
  <label className="field-block"><span className="field-label">Description</span><textarea className="input textarea" name="description" defaultValue={item?.description??""}/></label>
  <label className="field-block"><span className="field-label">Action summary</span><textarea className="input textarea" name="actionSummary" defaultValue={item?.action_summary??""}/></label>
  <label className="field-block"><span className="field-label">Customer note</span><textarea className="input textarea" name="customerNote" defaultValue={item?.customer_note??""}/></label>
  <label className="field-block"><span className="field-label">Internal note</span><textarea className="input textarea" name="internalNote" defaultValue={item?.internal_note??""}/></label>
  <label className="field-block"><span className="field-label">Checklist requirements (one per line)</span><textarea className="input textarea" name="checklistRequirements" defaultValue={item?.checklist_requirements??""}/></label>
  <div className="action-row"><button className="button button-primary" disabled={saving}>{saving?"Saving…":item?"Save work item":"Add work item"}</button>{onClose?<button type="button" className="button button-secondary" onClick={onClose}>Cancel</button>:null}<Message value={message}/></div></form>;
}

export function WorkItemManager({ projectId, items }: { projectId: string; items: Item[] }) {
  const router=useRouter();const[editing,setEditing]=useState<string|null>(null);const[message,setMessage]=useState<string|null>(null);const[busy,setBusy]=useState(false);
  async function action(item:Item,type:string){let reason:string|null=null;if(["defer","rework"].includes(type)){reason=window.prompt(type==="defer"?"Reason for deferral":"Reason for rework");if(!reason)return}setBusy(true);try{await request(`/api/project-items/${item.id}/manage`,"PATCH",{action:type,reason});router.refresh()}catch(e){setMessage(e instanceof Error?e.message:"Action failed.")}finally{setBusy(false)}}
  async function remove(item:Item){if(!window.confirm(`Delete “${item.title}”? This cannot be undone.`))return;setBusy(true);try{await request(`/api/project-items/${item.id}/manage`,"DELETE");router.refresh()}catch(e){setMessage(e instanceof Error?e.message:"Delete failed.")}finally{setBusy(false)}}
  async function move(index:number,direction:number){const next=[...items];const target=index+direction;if(target<0||target>=next.length)return;[next[index],next[target]]=[next[target],next[index]];setBusy(true);try{await request(`/api/projects/${projectId}/items`,"PATCH",{itemIds:next.map(i=>i.id)});router.refresh()}catch(e){setMessage(e instanceof Error?e.message:"Reorder failed.")}finally{setBusy(false)}}
  return <div className="page-stack"><details className="management-details"><summary>Add work item</summary><WorkItemForm projectId={projectId}/></details><Message value={message}/>{items.map((item,index)=><article className="panel work-item-admin-card" key={item.id}><div className="panel-header"><div><p className="eyebrow">{item.priority_code} · {item.is_add_on?`Add-on ${item.add_on_status}`:"Base scope"}</p><h3>{item.title}</h3></div><div className="action-row"><button className="button button-secondary" disabled={busy||index===0} onClick={()=>move(index,-1)}>↑</button><button className="button button-secondary" disabled={busy||index===items.length-1} onClick={()=>move(index,1)}>↓</button><button className="button button-secondary" onClick={()=>setEditing(editing===item.id?null:item.id)}>Edit</button></div></div>
    {editing===item.id?<WorkItemForm projectId={projectId} item={item} onClose={()=>setEditing(null)}/>:<><p>{item.description??"No description"}</p><div className="details-grid"><div><dt>Quoted</dt><dd>${Number(item.quoted_amount).toFixed(2)}</dd></div><div><dt>Tracked cost</dt><dd>${(Number(item.actual_cost)+Number(item.labour_cost)+Number(item.material_cost)).toFixed(2)}</dd></div><div><dt>Checklist</dt><dd>{item.checklist_requirements??"None"}</dd></div><div><dt>Deferral</dt><dd>{item.deferred_reason??"Active"}</dd></div></div><div className="action-row">{item.is_deferred?<button className="button button-secondary" disabled={busy} onClick={()=>action(item,"reopen")}>Reopen</button>:<button className="button button-secondary" disabled={busy} onClick={()=>action(item,"defer")}>Defer</button>}<button className="button button-secondary" disabled={busy} onClick={()=>action(item,"rework")}>Return for rework</button>{item.is_add_on&&item.add_on_status==="proposed"?<><button className="button button-primary" onClick={()=>action(item,"approve_add_on")}>Approve add-on</button><button className="button button-danger" onClick={()=>action(item,"reject_add_on")}>Reject add-on</button></>:null}<button className="button button-danger" disabled={busy} onClick={()=>remove(item)}>Delete</button></div>{item.project_item_events?.length?<details className="management-details"><summary>History ({item.project_item_events.length})</summary>{item.project_item_events.map(e=><p className="helper-text" key={e.id}>{new Date(e.created_at).toLocaleString()} — {e.event_type.replaceAll("_"," ")}{e.reason?`: ${e.reason}`:""}</p>)}</details>:null}</>}
  </article>)}</div>;
}

export function ScopeChangeManager({projectId,items,changes}:{projectId:string;items:Item[];changes:Change[]}){const router=useRouter();const[message,setMessage]=useState<string|null>(null);async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();try{await request(`/api/projects/${projectId}/scope-changes`,"POST",Object.fromEntries(new FormData(e.currentTarget)));e.currentTarget.reset();router.refresh()}catch(error){setMessage(error instanceof Error?error.message:"Save failed.")}}async function decide(id:string,status:string){try{await request(`/api/projects/${projectId}/scope-changes`,"PATCH",{changeId:id,status});router.refresh()}catch(error){setMessage(error instanceof Error?error.message:"Decision failed.")}}return <div className="page-stack"><form className="stack-form" onSubmit={submit}><div className="form-grid"><label className="field-block"><span className="field-label">Change type</span><select className="input input-select" name="changeType"><option value="scope_change">Scope change</option><option value="add_on">Add-on</option><option value="rework">Rework</option><option value="deferral">Deferral</option></select></label><label className="field-block"><span className="field-label">Work item</span><select className="input input-select" name="projectItemId"><option value="">Whole project</option>{items.map(i=><option value={i.id} key={i.id}>{i.title}</option>)}</select></label><label className="field-block"><span className="field-label">Requested by</span><input className="input" name="requestedBy"/></label><label className="field-block"><span className="field-label">Amount change</span><input className="input" type="number" step="0.01" name="amountDelta" defaultValue="0"/></label></div><label className="field-block"><span className="field-label">Description</span><textarea className="input textarea" required name="description"/></label><button className="button button-primary">Record scope change</button></form><Message value={message}/>{changes.map(c=><article className="review-draft-row" key={c.id}><div><strong>{c.change_type.replaceAll("_"," ")}</strong><p>{c.description}</p></div><span>{c.status}</span><span>{Number(c.amount_delta)>=0?"+":""}${Number(c.amount_delta).toFixed(2)}</span>{c.status==="proposed"?<div className="action-row"><button className="button button-primary" onClick={()=>decide(c.id,"approved")}>Approve</button><button className="button button-danger" onClick={()=>decide(c.id,"rejected")}>Reject</button></div>:null}</article>)}</div>}

export function ProjectTeamManager({projectId,staff,members}:{projectId:string;staff:Option[];members:TeamMember[]}){const router=useRouter();const[message,setMessage]=useState<string|null>(null);async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);try{await request(`/api/projects/${projectId}/team`,"POST",{...Object.fromEntries(form),isLead:form.has("isLead")});router.refresh()}catch(error){setMessage(error instanceof Error?error.message:"Save failed.")}}async function remove(profileId:string){try{await request(`/api/projects/${projectId}/team`,"DELETE",{profileId});router.refresh()}catch(error){setMessage(error instanceof Error?error.message:"Remove failed.")}}return <div className="page-stack"><form className="form-grid" onSubmit={submit}><label className="field-block"><span className="field-label">Staff member</span><select className="input input-select" name="profileId" required><option value="">Select</option>{staff.map(s=><option key={s.id} value={s.id}>{s.label}</option>)}</select></label><label className="field-block"><span className="field-label">Team role</span><input className="input" name="teamRole" defaultValue="worker"/></label><label className="toggle-row"><input type="checkbox" name="isLead"/><span>Team lead</span></label><button className="button button-primary">Add / update</button></form><Message value={message}/>{members.map(member=>{const p=Array.isArray(member.profile)?member.profile[0]:member.profile;return <div className="review-draft-row" key={member.profile_id}><strong>{p?.display_name??"Staff member"}</strong><span>{member.team_role}</span><span>{member.is_lead?"Lead":"Member"}</span><button className="button button-danger" onClick={()=>remove(member.profile_id)}>Remove</button></div>})}</div>}
